---
reveal-root: https://cdn.rawgit.com/hakimel/reveal.js/3.3.0
css-root: https://cdn.rawgit.com/olaurino/saturnine/master

logo: <img src="http://library.cfa.harvard.edu/files/wolbach/files/cfalogort.png">
bg-height: 2508
bg-width: 4288
bg-vert: 20
bg-horiz: 50
...
