---
reveal-root: https://cdn.rawgit.com/hakimel/reveal.js/3.1.0 
css-root: https://cdn.rawgit.com/olaurino/presentations/master/common

logo: <img src="http://library.cfa.harvard.edu/files/wolbach/files/cfalogort.png"> 
venue: venue 
bg-height: 2508
bg-width: 4288
bg-vert: 20
bg-horiz: 50
...

